# fly.toml app configuration file for uptimepulse-alloy

app = "uptimepulse-alloy"
primary_region = "sin"

[build]
  image = "grafana/alloy:latest"

[[files]]
  guest_path = "/etc/alloy/config.hcl"
  local_path = "alloy.hcl"

[processes]
  app = "run /etc/alloy/config.hcl"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
