apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iyup.fullname" . }}-alertmanager-smtp
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
type: Opaque
data:
  SMTP_SMARTHOST: {{ .Values.alert.smtp.smarthost | b64enc }}
  SMTP_FROM: {{ .Values.alert.smtp.from | b64enc }}
  SMTP_USERNAME: {{ .Values.alert.smtp.user | b64enc }}
  SMTP_PASSWORD: {{ .Values.alert.smtp.password | b64enc }}
  SMTP_TO: {{ .Values.alert.smtp.to | b64enc }}
