apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iyup.fullname" . }}-alertmanager
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "iyup.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{- include "iyup.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: {{ .Values.image.alertmanager | quote }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
          envFrom:
            - secretRef:
                name: {{ include "iyup.fullname" . }}-alertmanager-smtp
      volumes:
        - name: config
          configMap:
            name: {{ include "iyup.fullname" . }}-alertmanager-config
