apiVersion: v1
kind: Service
metadata:
  name: {{ include "iyup.fullname" . }}-alertmanager
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  selector:
    {{- include "iyup.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
  ports:
    - name: http
      port: {{ .Values.service.alertmanagerPort }}
      targetPort: 9093
