apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iyup.fullname" . }}-grafana
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "iyup.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "iyup.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.image.grafana | quote }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "iyup.fullname" . }}-grafana-data
