apiVersion: v1
kind: Service
metadata:
  name: {{ include "iyup.fullname" . }}-grafana
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  selector:
    {{- include "iyup.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.service.grafanaPort }}
      targetPort: 3000
  type: ClusterIP
