apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iyup.fullname" . }}-ping-targets
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
    app.kubernetes.io/component: ping-agent
data:
  targets.json: |
    {{- toJson .Values.pingTargets | nindent 4 }}
