apiVersion: v1
kind: Service
metadata:
  name: {{ include "iyup.fullname" . }}-ping-agent
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
    app.kubernetes.io/component: ping-agent
spec:
  selector:
    {{- include "iyup.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ping-agent
  ports:
    - name: http
      port: {{ .Values.service.pingAgentPort }}
      targetPort: 8080
