apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iyup.fullname" . }}-prometheus
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "iyup.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "iyup.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.image.prometheus | quote }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
            - name: rules
              mountPath: /etc/prometheus/rules
      volumes:
        - name: config
          configMap:
            name: {{ include "iyup.fullname" . }}-prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "iyup.fullname" . }}-prometheus-data
        - name: rules
          configMap:
            name: {{ include "iyup.fullname" . }}-prometheus-alert-rules
