apiVersion: v1
kind: Service
metadata:
  name: {{ include "iyup.fullname" . }}-prometheus
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  selector:
    {{- include "iyup.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: {{ .Values.service.prometheusPort }}
      targetPort: 9090
