apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iyup.fullname" . }}-prometheus-config
  labels:
    {{- include "iyup.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    rule_files:
      - /etc/prometheus/rules/alert.rules.yml

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - '{{ include "iyup.fullname" . }}-alertmanager:{{ .Values.service.alertmanagerPort }}'

    scrape_configs:
      - job_name: "api-gateway"
        static_configs:
          - targets:
              - '{{ include "iyup.fullname" . }}-api-gateway:{{ .Values.service.apiGatewayPort }}'
      - job_name: "ping-agent"
        static_configs:
          - targets:
              - '{{ include "iyup.fullname" . }}-ping-agent:{{ .Values.service.pingAgentPort }}'
