global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8080"]
  - job_name: "ping-agent"
    static_configs:
      - targets: ["ping-agent.default.svc.cluster.local:8080"]
