apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-logger
  template:
    metadata:
      labels:
        app: alert-logger
    spec:
      containers:
        - name: alert-logger
          image: mendhak/http-https-echo:36
          env:
            - name: LOG_WITHOUT_NEWLINE
              value: "true"
          ports:
            - containerPort: 8080
