apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptimepulse.fullname" . }}-alert-logger
  labels:
    {{- include "uptimepulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: alert-logger
spec:
  selector:
    {{- include "uptimepulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alert-logger
  ports:
    - name: http
      port: {{ .Values.service.alertLoggerPort }}
      targetPort: 8080
