apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptimepulse.fullname" . }}-api-gateway
  labels:
    {{- include "uptimepulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "uptimepulse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        {{- include "uptimepulse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.image.apiGateway | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PING_AGENT_METRICS_URL
              value: "http://{{ include \"uptimepulse.fullname\" . }}-ping-agent:8080/metrics"
            - name: PING_TARGET_URL
              value: "{{ index .Values.pingTargets 0 }}"
            - name: PING_TARGET_URLS
              value: "{{ join \",\" .Values.pingTargets }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
