apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptimepulse.fullname" . }}-api-gateway
  labels:
    {{- include "uptimepulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  selector:
    {{- include "uptimepulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  ports:
    - name: http
      port: {{ .Values.service.apiGatewayPort }}
      targetPort: 8080
