apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptimepulse.fullname" . }}-ping-agent
  labels:
    {{- include "uptimepulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: ping-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "uptimepulse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ping-agent
  template:
    metadata:
      labels:
        {{- include "uptimepulse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ping-agent
    spec:
      containers:
      - name: ping-agent
        image: {{ .Values.image.pingAgent | quote }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: PING_TARGET_URLS
            value: "{{ join \",\" .Values.pingTargets }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
