apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uptimepulse.fullname" . }}-ping-targets
  labels:
    {{- include "uptimepulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: ping-agent
data:
  targets.json: |
    {{- toJson .Values.pingTargets | nindent 4 }}
