apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uptimepulse.fullname" . }}-prometheus-data
  labels:
    {{- include "uptimepulse.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.pvcSize }}
